### ISSUE TITLE
Installation of plugin prevents initialisation of CKEditor

### ISSUE THREAD

**Issue by netcarver** [Toutouwai/headingscase#2]
Following the installation instructions prevents the CKEditor this is applied to from initializing correctly.

![ckeditor](https://user-images.githubusercontent.com/16049/31885412-53c51200-b7e8-11e7-9baf-4185e70e49a9.png)

The following error occurs in the JS Console...

    ckeditor.js:255 Uncaught TypeError: Cannot read property 'icons' of null
        at CKEDITOR.resourceManager.<anonymous> (ckeditor.js:255)
        at CKEDITOR.resourceManager.<anonymous> (ckeditor.js:254)
        at f (ckeditor.js:249)
        at Array.D (ckeditor.js:249)
        at w (ckeditor.js:249)
        at ckeditor.js:250
    (anonymous) @ ckeditor.js:255
    (anonymous) @ ckeditor.js:254
    f @ ckeditor.js:249
    D @ ckeditor.js:249
    w @ ckeditor.js:249
    (anonymous) @ ckeditor.js:250
    setTimeout (async)
    A.CKEDITOR.env.ie.f.$.onload @ ckeditor.js:250

Using PW 3.0.76 and CKEditor 4.7.3.

**Comment by Toutouwai** [comment]
Is the plugin folder named "headingscase"? GitHub adds the suffix "-master" which must be removed before installing the module.

**Comment by netcarver** [comment]
@Toutouwai Thanks, Robin, that was it. Perhaps a small mention of that in the readme?

**Comment by Toutouwai** [comment]
I have updated the readme.
